### ISSUE TITLE
Keep the Convo Rolling

### ISSUE THREAD

**Issue by gerardramos** [revelrylabs/storybot#1]
User Story:

## Background

The storybot is a CLI tool for interacting with the OpenAI API. This feature will allow users to keep the conversation with the OpenAI API open after the response. This will enable users to have a more natural conversation with the OpenAI API, and will provide a more seamless user experience.

## Scenario - Keep Conversation Open

- [ ] The user should be able to keep the conversation open with the OpenAI API after the response.
- [ ] The user should be able to continue the conversation with the OpenAI API without having to re-enter the command.
- [ ] The user should be able to view the conversation history with the OpenAI API.

## Implementation Notes

1. Create a function that will allow the user to keep the conversation open with the OpenAI API after the response.
2. Create a data structure to store the conversation history with the OpenAI API.
3. Create a function that will allow the user to view the conversation history with the OpenAI API.
4. Create a function that will allow the user to continue the conversation with the OpenAI API without having to re-enter the command.
5. Update the story

**Comment by Dacello** [comment]
This has been added with https://github.com/revelrylabs/storybot-ai/commit/b07394655e641feb962b58d3d4e3484046e97d86
